#!/bin/bash
# dotdrop
# =======
#
# Easily sync dotfiles between computers
# https://github.com/kanemathers/dotdrop
#
# How to Install
# --------------
#
# Source this file in ~/.bash_profile::
#
#     $ echo "[[ -f ~/dotdrop/dotdrop ]] && . ~/dotdrop/dotdrop" >> ~/.bash_profile
#

HERE=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd -P)

. "${HERE}/sync"

DOTDROP_SLEEP=${DOTDROP_SLEEP:-10}
DOTDROP_NOTIFY=${DOTDROP_NOTIFY:-"no"}

notify()
{
    local message=$1

    if [[ -z "$message" ]]; then
        return 1
    fi

    command -v notify-send >/dev/null 2>&1 || return 1

    notify-send "$message"

    return $?
}

dotdrop_sync()
{
    # Sleep long enough for an internet connection to be established and,
    # hopefully, long enough for dropbox to sync the plugins.
    sleep $DOTDROP_SLEEP

    remove_links

    for plugin in "$HERE"/plugins.d/*/*; do
        create_link "$plugin"
    done

    if [[ "$DOTDROP_NOTIFY" == "yes" ]]; then
        notify "dotdrop: finished syncing"
    fi
}

(dotdrop_sync &)
