#!/bin/bash

HERE=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd -P)

. "${HERE}/sync"

DOTDROP_NOTIFY=${DOTDROP_NOTIFY:-"no"}

notify()
{
    local message=$1

    if [ -z "$message" ]; then
        return 1
    fi

    command -v notify-send >/dev/null 2>&1 || return 1

    notify-send "$message"

    return $?
}

check_connection()
{
    ping -c 1 google.com >/dev/null 2>&1
}

dotdrop_sync()
{
    until check_connection; do
        sleep 5
    done

    remove_links

    for plugin in "$HERE"/plugins.d/*/*; do
        create_link "$plugin"
    done

    if [ "$DOTDROP_NOTIFY" == "yes" ]; then
        notify "dotdrop: finished syncing"
    fi
}

(dotdrop_sync &)
