#!/bin/bash

HISTORY=~/.dotdrop_history

remove_links()
{
    local link

    if [ ! -f $HISTORY ]; then
        return
    fi

    for link in $(cat $HISTORY); do
        if [ ! -L "$link" ]; then
            continue
        fi

        rm "$link"

        grep -v "$link" $HISTORY > "${HISTORY}.new" \
            && mv "${HISTORY}.new" $HISTORY
    done

    # XXX: why is this lingering?
    rm "${HISTORY}.new"
}

create_link()
{
    local file=$1
    local link_path="$HOME/.$(basename $file)"

    ln -s "$file" "$link_path" 2>/dev/null || return 1;

    echo "$link_path" >> $HISTORY
}
